// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnetfyjzvnzrexnehtzm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImduZXRmeWp6dm56cmV4bmVodHptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NDc3NzcsImV4cCI6MjA2MDAyMzc3N30.XGT3DmjxFW9W9OfWSOS4QDnl6MDolIz42GmFpE1QhFs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);